VEN-756 | Upgrade dependencies
City-of-Helsinki/berth-reservations-ui pull request #357
Opened 2021-01-11 13:42 UTC by TatuArvela

## Description :sparkles:

* Upgrade several dependencies that could easily be upgraded
* Sort package.json
* Rename all `*.spec.*` files to `*.test.*`
* Remove serviceWorker.ts

## Issues :bug:

### Closes :no_good_woman:

* [VEN-756](https://helsinkisolutionoffice.atlassian.net/browse/VEN-756): Upgrade react-router dependencies

2021-01-26 11:40 UTC, Nizar-Rahme requested changes
I left a couple of nitpicks, fantastic job overall 💎

2021-01-26 11:40 UTC, Nizar-Rahme commented on src/utils/unmarkedWinterStorage.ts
> +import _ from 'lodash';
For a smaller bundle size:
```suggestion
import orderBy from 'lodash/orderBy';
```

2021-01-26 11:40 UTC, Nizar-Rahme commented on src/components/forms/fragments/overview/bigShipsInfo/BigShipsInfo.tsx
> +  const rentingPeriodWDates = `${rentingPeriodLabel} ${rentFrom ? rentFrom : ''}-${rentTill ? rentTill : ''}`;
```suggestion
  const rentingPeriodWDates = `${rentingPeriodLabel} ${rentFrom || ''}-${rentTill || ''}`;
```

2021-01-26 11:40 UTC, Nizar-Rahme commented on src/components/forms/fragments/exchangeApplication/ExchangeApplicationContainer.tsx
> +        const reasons = data && data.berthSwitchReasons ? data.berthSwitchReasons.filter(isReason) : [];
```suggestion
        const reasons = data?.berthSwitchReasons ? data.berthSwitchReasons.filter(isReason) : [];
```

2021-01-27 13:34 UTC, TatuArvela commented on src/@types/piwik-react-router.d.ts
> +    // eslint-disable-next-line @typescript-eslint/ban-types
Yep, I'll remove this.
I actually temporarily disabled this rule globally, we need to fix each of those separately later.

2021-01-27 14:31 UTC, Nizar-Rahme approved these changes
Great improvements! 🎖️

2021-01-27 14:46 UTC, merged